CREATE TABLE IF NOT EXISTS `destaques` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `titulo` VARCHAR(100) NOT NULL ,
  `link` VARCHAR(150) NOT NULL ,
  `imagem` VARCHAR(150) NOT NULL ,
  `ativo` TINYINT(1)  NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`id`) )
ENGINE = innoDB;