algoritmo "semnome"
// Função :
// Autor :
// Data : 30/08/2011
// Seção de Declarações 
var
      n : vetor [0..4] de inteiro
      i: inteiro
inicio

      para i de 0 ate 4 passo 1 faca
             escreval("Entre com o valor de n[",i,"]:")
             leia(n[i])
      fimpara

      
      escreva("O vetor n:")
      para i de 0 ate 4 passo 1 faca
             escreva(" ",n[i])
      fimpara

fimalgoritmo
